
name: Run Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (skip this if you use a different language)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate version of Node.js for your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run Tests
        run: npm test

      # Upload test reports (for example, JUnit or other format)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: path/to/test/report.xml  # Adjust this path based on your test framework

      # Optionally, upload code coverage reports
      - name: Upload coverage report
        if: success()  # Only upload if the tests pass
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: path/to/coverage-report  # Adjust path to where your coverage report is generated

  


  